#!/bin/sh

### BEGIN INIT INFO
# Provides:        timesyncd
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start timesync daemon
### END INIT INFO

. /lib/lsb/init-functions

NAME=timesyncd
DAEMON=/usr/bin/timesyncd
PIDFILE=/var/run/$NAME.pid
DAEMON_OPTS="/etc/timesyncd/timesyncd.conf"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/usr/bin"

case $1 in
	start)
		log_daemon_msg "Starting time synchronization server" "$NAME"
		start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping time synchronization server" "$NAME"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE		
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart)
		log_daemon_msg "Restarting time synchronization server" "$NAME"
		start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
		start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
		;;
	status)
		status_of_proc $DAEMON "Time synchronization server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 2
		;;
esac