#!/bin/sh

### BEGIN INIT INFO
# Provides: timesyncd
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start time synchronization server
# Description: Enable service provided by timesyncd.
### END INIT INFO

case "$1" in
'start')
        echo -n "Starting timesyncd."
        /etc/timesyncd/timesyncd.sh &
        ;;
'stop')
        echo -n "Shutting down timesyncd."
        killall -TERM timesyncd
        ;;
'restart')
        echo -n "Restarting timesyncd."
        killall -TERM timesyncd
        /etc/timesyncd/timesyncd.sh &

        ;;
*)
        echo "Usage: $0 { start | stop | restart }"
        ;;
esac
exit 0